### ISSUE TITLE
Split out non-main logic into package

### ISSUE THREAD

**Issue by richardmarshall** [askcom/dnsbench#11]
To simplify the process of refactoring the CLI UX we should move as much of the non argument/flag parsing and output logic into a package that can be imported.

The API exported by the package does not need to be built with users other than the cli tool at this point.

**Comment by Benco1** [comment]
@richardmarshall I kind of see non-main logic as potentially being two packages: 1) handles lookup and 2) does util stuff (i.e., reading/parsing and reporting). What do you think? Reasonable? Overkill?

**Comment by richardmarshall** [comment]
That sounds fine to me. With that said, try and keep what you do for this specific task as simple as possible. We'll be circling back to the package/API design after the UX refactor is complete.
